version: '3.9'

services:

  db:
    image: postgres:14.3-alpine3.15
    ports:
      - "5431:5432"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}